### ISSUE TITLE
Team 111 the-sun-beams code review

### ISSUE THREAD

**Issue by vanheaven-ui** [uimarshall/apple-webpage-clone#2]
- class name banner-text could be used for the header tag. 
- You could use the class hero for the section.
- if you use section tag, semantics require an h2-h6 tag within the section. you could hide its display.
- width of the nav needs to be checked.

**Comment by uimarshall** [comment]
> * class name banner-text could be used for the header tag.
> * You could use the class hero for the section.
> * if you use section tag, semantics require an h2-h6 tag within the section. you could hide its display.
> * width of the nav needs to be checked.

Thanks @vanheaven-ui , this had been attended to.
